/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdio.h>
#include <GPIO_lib.h>
#include <string.h>
#include <stdlib.h>
#include <time.h>


#include<TIMER_lib.h>


void GPIOInits(void){
	GPIO_Handle_t GPIOPins;

	//PUSH_BUTTON
	GPIOPins.GPIO_Regdef = GPIOA;
	GPIOPins.GPIO_config.Pin_Mode = GPIO_MODE_ALTERNATE;
	GPIOPins.GPIO_config.Pin_Output_Type = GPIO_PUSH_PULL;
	GPIOPins.GPIO_config.Pin_Pull= GPIO_NO_PULL;
	GPIOPins.GPIO_config.Pin_Speed = GPIO_SPEED_HIGH;
	GPIOPins.GPIO_config.Pin_alt_func = AF_1;
	GPIOPins.GPIO_config.Pin_Number = GPIO_PIN_0;
	GPIO_Init(&GPIOPins);

	GPIOPins.GPIO_Regdef = GPIOE;
	GPIOPins.GPIO_config.Pin_Mode = GPIO_MODE_OUTPUT;
	GPIOPins.GPIO_config.Pin_Output_Type = GPIO_PUSH_PULL;
	GPIOPins.GPIO_config.Pin_Pull= GPIO_PULL_DOWN;
	GPIOPins.GPIO_config.Pin_Speed = GPIO_SPEED_HIGH;

	//STM32_LEDS
	GPIOPins.GPIO_config.Pin_Number = GPIO_PIN_8;
	GPIO_Init(&GPIOPins);
	GPIOPins.GPIO_config.Pin_Number = GPIO_PIN_9;
	GPIO_Init(&GPIOPins);
	GPIOPins.GPIO_config.Pin_Number = GPIO_PIN_10;
	GPIO_Init(&GPIOPins);
	GPIOPins.GPIO_config.Pin_Number = GPIO_PIN_11;
	GPIO_Init(&GPIOPins);
	GPIOPins.GPIO_config.Pin_Number = GPIO_PIN_12;
	GPIO_Init(&GPIOPins);
	GPIOPins.GPIO_config.Pin_Number = GPIO_PIN_13;
	GPIO_Init(&GPIOPins);
	GPIOPins.GPIO_config.Pin_Number = GPIO_PIN_14;
	GPIO_Init(&GPIOPins);
	GPIOPins.GPIO_config.Pin_Number = GPIO_PIN_15;
	GPIO_Init(&GPIOPins);

	GPIO_WritePort(GPIOE, GPIO_PIN_SET);

}


int main (void){

	//INIT
	printf("Program measure time between button clicks... PRESS THE BUTTON \n");
	PeriClockControl(GPIOE, CLOCK_ENABLE);
	PeriClockControl(GPIOA, CLOCK_ENABLE);

	GPIOInits();

	Timer_Handle_t timer_2;
	Timer_Handle_t timer_3;

////TIMER2////
	timer_2.TIMER = TIMER2;
	//MAX arr value
	timer_2.TIM_ARR = 0xFFFFFFFFUL;
	//8 000 000 / 8000 = 1000 =>  0.1ms precision
	timer_2.TIM_PRESCALLER = (8000-1);
	timer_2.TIM_COUNTER_mode = COUNTER_MODE_UP;
	timer_2.TIM_EDGE_TRIGGER = TIM_EDGE_RISING;
	timer_2.TIM_INT_PRSC = TIM_INTERRUPT_1_EVENT;
	timer_2.TIM_FILTERING = TIM_FILTERING_NO;
	Timer_Init_INPUT_CC_MODE(&timer_2);
	TIMER_interrupt_set(timer_2.TIMER);
///////////////

/////TIMER3////
	timer_3.TIMER = TIMER3;
	timer_3.TIM_ARR = (1000-1);
	timer_3.TIM_PRESCALLER = (800-1);
	timer_3.TIM_COUNTER_mode= COUNTER_MODE_DOWN;
	timer_3.TIM_ONEPULSE = 0;

	Timer_Init_FREE_RUN(&timer_3);
	TIMER_interrupt_set(timer_3.TIMER);
////////////////

	while(1){
	}
	return 0;
}



void TIM2_IRQHandler(){
	Timer_IRQ_handling(TIMER2);
	Timer_indicate_time(TIMER2);

}

void TIM3_IRQHandler(){
	//Reset timer flag
	Timer_IRQ_handling(TIMER3);
	static int zmienna = 8;

	GPIO_TogglePin(GPIOE, zmienna++);
	if(zmienna == 16){
		zmienna = 8;
		}
}
