/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <GPIO_lib.h>
#include <TIMER_lib.h>
#include <stdio.h>


void pin_init(){

	PeriClockControl(GPIOA, CLOCK_ENABLE);

	PeriClockControl(GPIOE, CLOCK_ENABLE);

	GPIO_Handle_t GPIO_def;
	GPIO_def.GPIO_config.Pin_Number = GPIO_PIN_0;
	GPIO_def.GPIO_config.Pin_Mode = GPIO_MODE_INPUT;
	GPIO_def.GPIO_config.Pin_Output_Type = GPIO_PUSH_PULL;
	GPIO_def.GPIO_config.Pin_Pull = GPIO_NO_PULL;
	GPIO_def.GPIO_config.Pin_Speed = GPIO_SPEED_HIGH;
	GPIO_def.GPIO_Regdef = GPIOA;

	GPIO_Init(&GPIO_def);

	GPIO_interrupt_set(EDGE_BOTH, GPIO_PIN_0);

	GPIO_IRQITConfig(6, ENABLE);

	GPIO_def.GPIO_config.Pin_Number = GPIO_PIN_8;
	GPIO_def.GPIO_config.Pin_Mode = GPIO_MODE_OUTPUT;
	GPIO_def.GPIO_config.Pin_Output_Type = GPIO_PUSH_PULL;
	GPIO_def.GPIO_config.Pin_Pull = GPIO_NO_PULL;
	GPIO_def.GPIO_config.Pin_Speed = GPIO_SPEED_HIGH;
	GPIO_def.GPIO_Regdef = GPIOE;
	GPIO_Init(&GPIO_def);

	GPIO_def.GPIO_config.Pin_Number = GPIO_PIN_9;
	GPIO_Init(&GPIO_def);
	GPIO_def.GPIO_config.Pin_Number = GPIO_PIN_10;
	GPIO_Init(&GPIO_def);
	GPIO_def.GPIO_config.Pin_Number = GPIO_PIN_11;
	GPIO_Init(&GPIO_def);
	GPIO_def.GPIO_config.Pin_Number = GPIO_PIN_12;
	GPIO_Init(&GPIO_def);
	GPIO_def.GPIO_config.Pin_Number = GPIO_PIN_13;
	GPIO_Init(&GPIO_def);
	GPIO_def.GPIO_config.Pin_Number = GPIO_PIN_14;
	GPIO_Init(&GPIO_def);
	GPIO_def.GPIO_config.Pin_Number = GPIO_PIN_15;
	GPIO_Init(&GPIO_def);
	
	GPIO_WritePort(GPIOE, GPIO_PIN_SET);
}

int main(void)
{
    uint8_t PIN_NO = 0;
	pin_init();

	Timer_Handle_t timer;
	timer.TIMER = TIMER2;
	timer.TIM_ARR = (1000-1);
	timer.TIM_PRESCALLER = 8000;
	timer.TIM_COUNTER_mode= COUNTER_MODE_DOWN;
	timer.TIM_ONEPULSE = 0;
	//timer.TIM_OnePulse_mode = 1;

	Timer_Init_FREE_RUN(&timer);
	TIMER_interrupt_set(timer.TIMER);

	/* Loop forever */
	while(1)
	{
		// for(int i = 0; i < 0xFFFFF; i++)
		// {

		// }
    
        // switch(PIN_NO)
        // {
        //     case 0:
        //     {
        //         GPIO_TogglePin(GPIOE, GPIO_PIN_8);
        //         PIN_NO++;
        //         break;
        //     }

        //     case 1:
        //     {
        //         GPIO_TogglePin(GPIOE, GPIO_PIN_11);
        //         PIN_NO++;
        //         break;
        //     }

        //     case 2:
        //     {
        //         GPIO_TogglePin(GPIOE, GPIO_PIN_15);
        //         PIN_NO = 0;
        //         break;
        //     }
        // }

	}


}

void TIM2_IRQHandler(void){
//Reset timer flag

Timer_IRQ_handling(TIMER2);
static int zmienna = 8;

GPIO_TogglePin(GPIOE, zmienna++);
if(zmienna == 16){
	zmienna = 8;
	}

}


void EXTI0_IRQHandler (void){
	printf("HELLO from IRQ EXTI0\n");
	GPIO_IRQHandling(GPIO_PIN_0);
}
