/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <GPIO_lib.h>
#include <stdio.h>


void pin_init(){

	PeriClockControl(GPIOA, CLOCK_ENABLE);

	GPIO_Handle_t GPIO_def;
	GPIO_def.GPIO_config.Pin_Number = GPIO_PIN_0;
	GPIO_def.GPIO_config.Pin_Mode = GPIO_MODE_INPUT;
	GPIO_def.GPIO_config.Pin_Output_Type = GPIO_PUSH_PULL;
	GPIO_def.GPIO_config.Pin_Pull = GPIO_NO_PULL;
	GPIO_def.GPIO_config.Pin_Speed = GPIO_SPEED_HIGH;

	GPIO_def.GPIO_Regdef = GPIOA;

	GPIO_Init(&GPIO_def);
	GPIO_interrupt_set(EDGE_RISING, GPIO_PIN_0);
	GPIO_IRQITConfig(6, ENABLE);
}

int main(void)
{
	pin_init();

	/* Loop forever */
	for(;;);
}

void EXTI0_IRQHandler (void){
	printf("HELLO from IRQ EXTI0\n");
	GPIO_IRQHandling(GPIO_PIN_0);
}
