/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include<stm32f3xx.h>
#include <GPIO_lib.h>


void UARTGPIOInit(void){
//GPIO_RegDef_t* GPIO = (GPIO_RegDef_t*)GPIOE;

PeriClockControl(GPIOA, CLOCK_ENABLE);

GPIO_Handle_t GPIO_Pins ;

GPIO_Pins.GPIO_Regdef = GPIOA;

GPIO_Pins.GPIO_config.Pin_Mode = GPIO_MODE_ALTERNATE;
GPIO_Pins.GPIO_config.Pin_Output_Type = GPIO_PUSH_PULL;
GPIO_Pins.GPIO_config.Pin_Pull = GPIO_PULL_DOWN;
GPIO_Pins.GPIO_config.Pin_Speed = GPIO_SPEED_HIGH;
GPIO_Pins.GPIO_config.Pin_alt_func = AF_7;

GPIO_Pins.GPIO_config.Pin_Number = GPIO_PIN_9;
GPIO_Init(&GPIO_Pins);

GPIO_Pins.GPIO_config.Pin_Number = GPIO_PIN_10;
GPIO_Init(&GPIO_Pins);

}

/*
 * Character transmission procedure
1. Program the M bits in USART_CR1 to define the word length.
2. Select the desired baud rate using the USART_BRR register.
3. Program the number of stop bits in USART_CR2.
4. Enable the USART by writing the UE bit in USART_CR1 register to 1.
5. Select DMA enable (DMAT) in USART_CR3 if multibuffer communication is to take
place. Configure the DMA register as explained in multibuffer communication.
6. Set the TE bit in USART_CR1 to send an idle frame as first transmission.
7. Write the data to send in the USART_TDR register (this clears the TXE bit). Repeat this
for each data to be transmitted in case of single buffer.
8. After writing the last data into the USART_TDR register, wait until TC=1. This indicates
that the transmission of the last frame is complete. This is required for instance when
the USART is disabled or enters the Halt mode to avoid corrupting the last
transmission.
Single byte communication
Clearing the TXE bit is always performed by a write to the transmit data register.
The TXE bit is set by hardware and it indicates:
• The data has been moved from the USART_TDR register to the shift register and the
data transmission has started.
• The USART_TDR register is empty.
• The next data can be written in the USART_TDR register without overwriting the
previous data.
This flag generates an interrupt if the TXEIE bit is set.
 */
void UARTInit(void){
	//turn on UART clock
	RCC->APB2ENR |= (1 << 14);

USART_RegDef_t *UART = (USART_RegDef_t *)USART_1_BASEADDR;
	//1. Program the M bits in USART_CR1 to define the word length.
	//M[1:0] = 00: 1 Start bit, 8 data bits, n stop bits
		UART->USART_CR1 &= ~(1 << 28);
	//2. Select the desired baud rate using the USART_BRR register.
		// BRR = SYSCLK/BAUD = 8000000/9600 = 833 =>0x341
		UART->USART_BRR = 0x341;
	//3. Program the number of stop bits in USART_CR2. 1 stopbit
		UART->USART_CR1 &= ~(3 << 12);
	//4. Enable the USART by writing the UE bit in USART_CR1 register to 1.
		UART->USART_CR1 |= (1<<0);
	//6. Set the TE bit in USART_CR1 to send an idle frame as first transmission.
		UART->USART_CR1 |= (1<<3);
	//7. Write the data to send in the USART_TDR register (this clears the TXE bit). Repeat this
	//	for each data to be transmitted in case of single buffer.
		UART->USART_TDR = 'L';
	/*
	 * 8. After writing the last data into the USART_TDR register, wait until TC=1. This indicates
		that the transmission of the last frame is complete. This is required for instance when
		the USART is disabled or enters the Halt mode to avoid corrupting the last
		transmission.
	 */
		while(!(UART->USART_ISR & (1 << 6)));
		UART->USART_TDR = 'O';
		while(!(UART->USART_ISR & (1 << 6)));
		UART->USART_TDR = 'L';
		while(!(UART->USART_ISR & (1 << 6)));
		UART->USART_CR1 &= ~(1<<0);

}

int main(void)
{


	printf("HELLO WORLD\n");
	UARTGPIOInit();
	UARTInit();
	/* Loop forever */
	for(;;);
}
